/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f9fa',
        'surface-container': '#edeeef',
        'primary-container': '#4f46e5',
        'surface-dim': '#d9dadb',
        'error': '#ba1a1a',
        'tertiary-container': '#885500',
        'surface-container-high': '#e7e8e9',
        'on-tertiary-container': '#ffd4a4',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'outline': '#777587',
        'on-primary-fixed': '#0f0069',
        'on-primary-container': '#dad7ff',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary-fixed': '#2a1700',
        'outline-variant': '#c7c4d8',
        'surface': '#f8f9fa',
        'on-error-container': '#93000a',
        'on-surface-variant': '#464555',
        'secondary': '#006a61',
        'on-surface': '#191c1d',
        'surface-tint': '#4d44e3',
        'tertiary': '#684000',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#6bd8cb',
        'surface-container-highest': '#e1e3e4',
        'on-primary-fixed-variant': '#3323cc',
        'on-secondary': '#ffffff',
        'on-background': '#191c1d',
        'primary': '#3525cd',
        'surface-container-low': '#f3f4f5',
        'inverse-surface': '#2e3132',
        'on-secondary-container': '#006f66',
        'secondary-container': '#86f2e4',
        'background': '#f8f9fa',
        'on-secondary-fixed-variant': '#005049',
        'inverse-on-surface': '#f0f1f2',
        'on-secondary-fixed': '#00201d',
        'surface-variant': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e2dfff',
        'secondary-fixed': '#89f5e7',
        'on-tertiary-fixed-variant': '#653e00',
        'inverse-primary': '#c3c0ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'base': '4px',
        'gutter': '16px',
        'margin-desktop': '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

